.TH clsyc 1 "October 13, 2021"
.LO 1
.SH NAME
clsyc \- clears system cache and shows you the before and after results
.SH SYNOPSIS
.B clsyc

.SH DESCRIPTION
.B clsyc
clears all appcache (temporary files) that may have been dumped and forgotten about. Prints out a before size, and an after size on the user directory

.SH TIPS
Make sure to back up any files you may need from the /Library/Cache directory.

.SH AUTHOR
Aaron Menadue <amenadue@student.42adel.org.au> is the Lead Developer of '42 Vogship'.

.SH SEE ALSO
.BR cls (1),
.BR medir (1),
.BR vogship (1)
