.TH medir 1 "October 13, 2021"
.LO 1
.SH NAME
medir \- Makes and Enters a directory

.SH SYNOPSIS
.B medir
.RB [directory]

.SH DESCRIPTION
.B medir
is made for ease of access. Sometimes you just want to enter a directory you just made because you want to get creating. Thats the main purpose of this command.

.SH TIPS
Use this instead of
.B mkdir
.B <dir>
and
.B cd
.B <dir> .
You'll never know you needed it untill you use it!

.SH AUTHOR
Aaron Menadue <amenadue@student.42adel.org.au> is the Lead Developer of '42 Vogship'.

.SH SEE ALSO
.BR cls (1),
.BR norm (1),
.BR car (1),
.BR vogship (1)
