.TH norm 1 "October 13, 2021"
.LO 1
.SH NAME
norm \- Runs Norminette on each file with the correct flags for both
.B .c
and
.B .o
files.

.SH SYNOPSIS
.B norm
.RB [\-flags]
.RB [files]

.SH DESCRIPTION
.B norm
is shorthand for norminette and all the confusing flags you have to remember. This command is made for ease of access making 42 a smooth voyage.

.SH AUTHOR
Aaron Menadue <amenadue@student.42adel.org.au> is the Lead Developer of '42 Vogship'.

.SH SEE ALSO
.BR compile (1),
.BR car (1),
.BR genhead (1),
.BR vogship (1)
