.TH rsthead 1 "March 25, 2022"
.LO 1
.SH NAME
rsthead \- Loops through files and removes the
.B :Stdheader
for each file.

.SH SYNOPSIS
.BR rsthead
.RB [files]

.SH DESCRIPTION
.B rsthead
Looks through all the specified files and removes a header for the files that already contain one.

.SH AUTHOR
Aaron Menadue <amenadue@student.42adel.org.au> is the Lead Developer of 'Vogship'.

.SH SEE ALSO
.BR genhead (1),
.BR norm (1),
.BR vogship (1)
