.TH vogship 1 "April 5, 2022"
.LO 1
.SH NAME
vogship \- 42 Vogship Home Command

.SH SYNOPSIS
.B vogship
.RB [\-flags]

.SH FLAGS
.BR -v[c[s]]
shows the version of the vogship you are running.
.BR c
compares the installed version with current version.
.BR s
silences if the installed version is up to date.

.BR -h
shows a list of commands you can use and a little information about each one.

.BR -u[f]
checks for updates.
.BR f
forces updates and/or reinstalls vogship.


.SH DESCRIPTION
.B vogship
is the command that allows you to interact with the way vogship works.

.SH LOOKOUT
.B vogship
is soon to have a big change including a lot more flags for a lot more functionality.

.SH AUTHOR
Aaron Menadue <amenadue@student.42adel.org.au> is the Lead Developer of '42 Vogship'.

.SH SEE ALSO
.BR car (1),
.BR clsyc (1),
.BR cls (1),
.BR compile (1),
.BR genhead (1),
.BR rsthead (1),
.BR medir (1),
.BR norm (1)
